//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GSSystem.Web.SurfaceWater {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        	protected global::System.Web.UI.WebControls.Label lblid;
		protected global::System.Web.UI.WebControls.TextBox txtProName;
		protected global::System.Web.UI.WebControls.TextBox txtWType;
		protected global::System.Web.UI.WebControls.TextBox txtType;
		protected global::System.Web.UI.WebControls.TextBox txtDowtherm;
		protected global::System.Web.UI.WebControls.TextBox txtWPNum;
		protected global::System.Web.UI.WebControls.TextBox txtWPHead;
		protected global::System.Web.UI.WebControls.TextBox txtWPFlow;
		protected global::System.Web.UI.WebControls.TextBox txtWPPower;
		protected global::System.Web.UI.WebControls.TextBox txtHEType;
		protected global::System.Web.UI.WebControls.TextBox txtHENum;
		protected global::System.Web.UI.WebControls.TextBox txtHEHeatArea;
		protected global::System.Web.UI.WebControls.TextBox txtSWITemp;
		protected global::System.Web.UI.WebControls.TextBox txtSWOTemp;
		protected global::System.Web.UI.WebControls.TextBox txtSWFlow;
		protected global::System.Web.UI.WebControls.TextBox txtDNum;
		protected global::System.Web.UI.WebControls.TextBox txtDType;
		protected global::System.Web.UI.WebControls.TextBox txtSWTSize;
		protected global::System.Web.UI.WebControls.TextBox txtSWTType;
		protected global::System.Web.UI.WebControls.TextBox txtWSPNum;
		protected global::System.Web.UI.WebControls.TextBox txtWSPPower;
		protected global::System.Web.UI.WebControls.TextBox txtPVFrequ;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
