//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GSSystem.Web.SeaWater {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtProName;
		protected global::System.Web.UI.WebControls.TextBox txtWType;
		protected global::System.Web.UI.WebControls.TextBox txtType;
		protected global::System.Web.UI.WebControls.TextBox txtDowtherm;
		protected global::System.Web.UI.WebControls.TextBox txtSWWellNum;
		protected global::System.Web.UI.WebControls.TextBox txtSWWellDep;
		protected global::System.Web.UI.WebControls.TextBox txtCWPNum;
		protected global::System.Web.UI.WebControls.TextBox txtCWPHead;
		protected global::System.Web.UI.WebControls.TextBox txtCWPFlow;
		protected global::System.Web.UI.WebControls.TextBox txtCWPPower;
		protected global::System.Web.UI.WebControls.TextBox txtExHeatType;
		protected global::System.Web.UI.WebControls.TextBox txtExHeatNum;
		protected global::System.Web.UI.WebControls.TextBox txtExHeatArea;
		protected global::System.Web.UI.WebControls.TextBox txtSWInTemp;
		protected global::System.Web.UI.WebControls.TextBox txtSWOutTemp;
		protected global::System.Web.UI.WebControls.TextBox txtSeaWaterFlow;
		protected global::System.Web.UI.WebControls.TextBox txtDesanderNum;
		protected global::System.Web.UI.WebControls.TextBox txtDesanderType;
		protected global::System.Web.UI.WebControls.TextBox txtSoftWTSize;
		protected global::System.Web.UI.WebControls.TextBox txtSoftWType;
		protected global::System.Web.UI.WebControls.TextBox txtWPNum;
		protected global::System.Web.UI.WebControls.TextBox txtWPpower;
		protected global::System.Web.UI.WebControls.TextBox txtPVariableFre;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
