//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GSSystem.Web.UndergroundWater {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtProName;
		protected global::System.Web.UI.WebControls.TextBox txtWType;
		protected global::System.Web.UI.WebControls.TextBox txtWellNum;
		protected global::System.Web.UI.WebControls.TextBox txtWEWNum;
		protected global::System.Web.UI.WebControls.TextBox txtRWNum;
		protected global::System.Web.UI.WebControls.TextBox txtWellDepth;
		protected global::System.Web.UI.WebControls.TextBox txtSWWExtract;
		protected global::System.Web.UI.WebControls.TextBox txtHeatTime;
		protected global::System.Web.UI.WebControls.TextBox txtCoolTime;
		protected global::System.Web.UI.WebControls.TextBox txtWPDiameter;
		protected global::System.Web.UI.WebControls.TextBox txtWPipe;
		protected global::System.Web.UI.WebControls.TextBox txtBWPDiameter;
		protected global::System.Web.UI.WebControls.TextBox txtBWPipe;
		protected global::System.Web.UI.WebControls.TextBox txtDModel;
		protected global::System.Web.UI.WebControls.TextBox txtWTIModel;
		protected global::System.Web.UI.WebControls.TextBox txtCPETModel;
		protected global::System.Web.UI.WebControls.TextBox txtCPETNum;
		protected global::System.Web.UI.WebControls.TextBox txtFWTSize;
		protected global::System.Web.UI.WebControls.TextBox txtWSPNum;
		protected global::System.Web.UI.WebControls.TextBox txtWPPower;
		protected global::System.Web.UI.WebControls.TextBox txtPVFreque;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
