//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GSSystem.Web.UndergroundWater {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblid;
	protected global::System.Web.UI.WebControls.Label lblProName;
	protected global::System.Web.UI.WebControls.Label lblWType;
	protected global::System.Web.UI.WebControls.Label lblWellNum;
	protected global::System.Web.UI.WebControls.Label lblWEWNum;
	protected global::System.Web.UI.WebControls.Label lblRWNum;
	protected global::System.Web.UI.WebControls.Label lblWellDepth;
	protected global::System.Web.UI.WebControls.Label lblSWWExtract;
	protected global::System.Web.UI.WebControls.Label lblHeatTime;
	protected global::System.Web.UI.WebControls.Label lblCoolTime;
	protected global::System.Web.UI.WebControls.Label lblWPDiameter;
	protected global::System.Web.UI.WebControls.Label lblWPipe;
	protected global::System.Web.UI.WebControls.Label lblBWPDiameter;
	protected global::System.Web.UI.WebControls.Label lblBWPipe;
	protected global::System.Web.UI.WebControls.Label lblDModel;
	protected global::System.Web.UI.WebControls.Label lblWTIModel;
	protected global::System.Web.UI.WebControls.Label lblCPETModel;
	protected global::System.Web.UI.WebControls.Label lblCPETNum;
	protected global::System.Web.UI.WebControls.Label lblFWTSize;
	protected global::System.Web.UI.WebControls.Label lblWSPNum;
	protected global::System.Web.UI.WebControls.Label lblWPPower;
	protected global::System.Web.UI.WebControls.Label lblPVFreque;


       
    }
}
