//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GSSystem.Web.WinterType {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtProName;
		protected global::System.Web.UI.WebControls.TextBox txtWType;
		protected global::System.Web.UI.WebControls.TextBox txtWWPWTemp;
		protected global::System.Web.UI.WebControls.TextBox txtWWRWTemp;
		protected global::System.Web.UI.WebControls.TextBox txtWHSSInWTemp;
		protected global::System.Web.UI.WebControls.TextBox txtWHSSBackWTemp;
		protected global::System.Web.UI.WebControls.TextBox txtWHSSCWater;
		protected global::System.Web.UI.WebControls.TextBox txtWUEWSTemp;
		protected global::System.Web.UI.WebControls.TextBox txtWUEBWTemp;
		protected global::System.Web.UI.WebControls.TextBox txtWUECircul;
		protected global::System.Web.UI.WebControls.TextBox txtWRTempeRange;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
