//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GSSystem.Web.SummerType {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        	protected global::System.Web.UI.WebControls.Label lblid;
		protected global::System.Web.UI.WebControls.TextBox txtProName;
		protected global::System.Web.UI.WebControls.TextBox txtWType;
		protected global::System.Web.UI.WebControls.TextBox txtSHSSInWTemp;
		protected global::System.Web.UI.WebControls.TextBox txtSHSSBackWTemp;
		protected global::System.Web.UI.WebControls.TextBox txtSHSSCWater;
		protected global::System.Web.UI.WebControls.TextBox txtSUEWSTemp;
		protected global::System.Web.UI.WebControls.TextBox txtSUEBWTemp;
		protected global::System.Web.UI.WebControls.TextBox txtSUECircul;
		protected global::System.Web.UI.WebControls.TextBox txtSRTempRange;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
