//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GSSystem.Web.WasteWater {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtProName;
		protected global::System.Web.UI.WebControls.TextBox txtWType;
		protected global::System.Web.UI.WebControls.TextBox txtType;
		protected global::System.Web.UI.WebControls.TextBox txtDowtherm;
		protected global::System.Web.UI.WebControls.TextBox txtSPNum;
		protected global::System.Web.UI.WebControls.TextBox txtSPHead;
		protected global::System.Web.UI.WebControls.TextBox txtSPFlow;
		protected global::System.Web.UI.WebControls.TextBox txtSPPower;
		protected global::System.Web.UI.WebControls.TextBox txtHEType;
		protected global::System.Web.UI.WebControls.TextBox txtHENum;
		protected global::System.Web.UI.WebControls.TextBox txtHEHEArea;
		protected global::System.Web.UI.WebControls.TextBox txtSInTemp;
		protected global::System.Web.UI.WebControls.TextBox txtSOutTemp;
		protected global::System.Web.UI.WebControls.TextBox txtSFlow;
		protected global::System.Web.UI.WebControls.TextBox txtWTIModel;
		protected global::System.Web.UI.WebControls.TextBox txtCPETMode;
		protected global::System.Web.UI.WebControls.TextBox txtCPETNum;
		protected global::System.Web.UI.WebControls.TextBox txtFWTSize;
		protected global::System.Web.UI.WebControls.TextBox txtWSPNum;
		protected global::System.Web.UI.WebControls.TextBox txtWSPPower;
		protected global::System.Web.UI.WebControls.TextBox txtPVFrequ;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
