//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GSSystem.Web.WasteWater {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblid;
	protected global::System.Web.UI.WebControls.Label lblProName;
	protected global::System.Web.UI.WebControls.Label lblWType;
	protected global::System.Web.UI.WebControls.Label lblType;
	protected global::System.Web.UI.WebControls.Label lblDowtherm;
	protected global::System.Web.UI.WebControls.Label lblSPNum;
	protected global::System.Web.UI.WebControls.Label lblSPHead;
	protected global::System.Web.UI.WebControls.Label lblSPFlow;
	protected global::System.Web.UI.WebControls.Label lblSPPower;
	protected global::System.Web.UI.WebControls.Label lblHEType;
	protected global::System.Web.UI.WebControls.Label lblHENum;
	protected global::System.Web.UI.WebControls.Label lblHEHEArea;
	protected global::System.Web.UI.WebControls.Label lblSInTemp;
	protected global::System.Web.UI.WebControls.Label lblSOutTemp;
	protected global::System.Web.UI.WebControls.Label lblSFlow;
	protected global::System.Web.UI.WebControls.Label lblWTIModel;
	protected global::System.Web.UI.WebControls.Label lblCPETMode;
	protected global::System.Web.UI.WebControls.Label lblCPETNum;
	protected global::System.Web.UI.WebControls.Label lblFWTSize;
	protected global::System.Web.UI.WebControls.Label lblWSPNum;
	protected global::System.Web.UI.WebControls.Label lblWSPPower;
	protected global::System.Web.UI.WebControls.Label lblPVFrequ;


       
    }
}
