//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GSSystem.Web.ProjectCommonCity {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtProName;
		protected global::System.Web.UI.WebControls.TextBox txtProAdd;
		protected global::System.Web.UI.WebControls.TextBox txtProType;
		protected global::System.Web.UI.WebControls.TextBox txtConUnit;
		protected global::System.Web.UI.WebControls.TextBox txtHpManufacturer;
		protected global::System.Web.UI.WebControls.TextBox txtFinTime;
		protected global::System.Web.UI.WebControls.TextBox txtCoveredArea;
		protected global::System.Web.UI.WebControls.TextBox txtHpType;
		protected global::System.Web.UI.WebControls.TextBox txtEngCharacter;
		protected global::System.Web.UI.WebControls.TextBox txtUseFormat;
		protected global::System.Web.UI.WebControls.TextBox txtTerminalForm;
		protected global::System.Web.UI.WebControls.TextBox txtProjectTHHp;
		protected global::System.Web.UI.WebControls.TextBox txtProjectTCHp;
		protected global::System.Web.UI.WebControls.TextBox txtHpEquipmentType;
		protected global::System.Web.UI.WebControls.TextBox txtHpEquipmentNum;
		protected global::System.Web.UI.WebControls.TextBox txtNominalHeat;
		protected global::System.Web.UI.WebControls.TextBox txtNominalCool;
		protected global::System.Web.UI.WebControls.TextBox txtHeatInputPower;
		protected global::System.Web.UI.WebControls.TextBox txtCoolInputPower;
		protected global::System.Web.UI.WebControls.TextBox txtWType;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
