//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GSSystem.Web.ProjectCommonCity {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblid;
	protected global::System.Web.UI.WebControls.Label lblProName;
	protected global::System.Web.UI.WebControls.Label lblProAdd;
	protected global::System.Web.UI.WebControls.Label lblProType;
	protected global::System.Web.UI.WebControls.Label lblConUnit;
	protected global::System.Web.UI.WebControls.Label lblHpManufacturer;
	protected global::System.Web.UI.WebControls.Label lblFinTime;
	protected global::System.Web.UI.WebControls.Label lblCoveredArea;
	protected global::System.Web.UI.WebControls.Label lblHpType;
	protected global::System.Web.UI.WebControls.Label lblEngCharacter;
	protected global::System.Web.UI.WebControls.Label lblUseFormat;
	protected global::System.Web.UI.WebControls.Label lblTerminalForm;
	protected global::System.Web.UI.WebControls.Label lblProjectTHHp;
	protected global::System.Web.UI.WebControls.Label lblProjectTCHp;
	protected global::System.Web.UI.WebControls.Label lblHpEquipmentType;
	protected global::System.Web.UI.WebControls.Label lblHpEquipmentNum;
	protected global::System.Web.UI.WebControls.Label lblNominalHeat;
	protected global::System.Web.UI.WebControls.Label lblNominalCool;
	protected global::System.Web.UI.WebControls.Label lblHeatInputPower;
	protected global::System.Web.UI.WebControls.Label lblCoolInputPower;
	protected global::System.Web.UI.WebControls.Label lblWType;


       
    }
}
