//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GSSystem.Web.SoilSource {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtProName;
		protected global::System.Web.UI.WebControls.TextBox txtWType;
		protected global::System.Web.UI.WebControls.TextBox txtPHoleNum;
		protected global::System.Web.UI.WebControls.TextBox txtHoleDepth;
		protected global::System.Web.UI.WebControls.TextBox txtHoleDistance;
		protected global::System.Web.UI.WebControls.TextBox txtUHEMaterial;
		protected global::System.Web.UI.WebControls.TextBox txtUHEDiameter;
		protected global::System.Web.UI.WebControls.TextBox txtHeatTime;
		protected global::System.Web.UI.WebControls.TextBox txtCoolTime;
		protected global::System.Web.UI.WebControls.TextBox txtBPFormat;
		protected global::System.Web.UI.WebControls.TextBox txtUHEUType;
		protected global::System.Web.UI.WebControls.TextBox txtUHESparallel;
		protected global::System.Web.UI.WebControls.TextBox txtUHETotalLen;
		protected global::System.Web.UI.WebControls.TextBox txtWTIModel;
		protected global::System.Web.UI.WebControls.TextBox txtCPETModel;
		protected global::System.Web.UI.WebControls.TextBox txtCPETNum;
		protected global::System.Web.UI.WebControls.TextBox txtFWTSize;
		protected global::System.Web.UI.WebControls.TextBox txtWSPNum;
		protected global::System.Web.UI.WebControls.TextBox txtWSPPower;
		protected global::System.Web.UI.WebControls.TextBox txtPVFreque;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
