//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GSSystem.Web.SoilSource {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblid;
	protected global::System.Web.UI.WebControls.Label lblProName;
	protected global::System.Web.UI.WebControls.Label lblWType;
	protected global::System.Web.UI.WebControls.Label lblPHoleNum;
	protected global::System.Web.UI.WebControls.Label lblHoleDepth;
	protected global::System.Web.UI.WebControls.Label lblHoleDistance;
	protected global::System.Web.UI.WebControls.Label lblUHEMaterial;
	protected global::System.Web.UI.WebControls.Label lblUHEDiameter;
	protected global::System.Web.UI.WebControls.Label lblHeatTime;
	protected global::System.Web.UI.WebControls.Label lblCoolTime;
	protected global::System.Web.UI.WebControls.Label lblBPFormat;
	protected global::System.Web.UI.WebControls.Label lblUHEUType;
	protected global::System.Web.UI.WebControls.Label lblUHESparallel;
	protected global::System.Web.UI.WebControls.Label lblUHETotalLen;
	protected global::System.Web.UI.WebControls.Label lblWTIModel;
	protected global::System.Web.UI.WebControls.Label lblCPETModel;
	protected global::System.Web.UI.WebControls.Label lblCPETNum;
	protected global::System.Web.UI.WebControls.Label lblFWTSize;
	protected global::System.Web.UI.WebControls.Label lblWSPNum;
	protected global::System.Web.UI.WebControls.Label lblWSPPower;
	protected global::System.Web.UI.WebControls.Label lblPVFreque;


       
    }
}
